<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        // \App\Models\users.nick_name::factory(10)->create();
        $wordAr=[
            ['title'=>'{stocks.name} 임직원 A씨 자택에서 숨쉰채 발견'],
            ['title'=>'투자자 {users.nick_name} 말하기를 {stocks.name}사 주식이 오를거라고 예상'],
            ['title'=>'{stocks.name}사 주식 {stocks.name}와 병합 M&A 계약 추진중'],
            ['title'=>'{users.nick_name}, {stocks.name}사 주식 풀매수 움직임 보여..'],
            ['title'=>'{users.nick_name}, {stocks.name}사 주식 풀매도 움직임 보여..'],
            ['title'=>'{users.nick_name}, {stocks.name}사 사옥 앞에서 소리벗고 빤스질러'],
            ['title'=>'{users.nick_name}, {stocks.name}사 직원 연봉이 오른다'],
            ['title'=>'{stocks.name}사 직원 집에서 졸다 보너스 지급받아 논란..'],
            ['title'=>'{stocks.name}사 직원 오늘은 치킨이닭'],
            ['title'=>'{users.nick_name} 대주주 총회에서 비키니차림으로 등장하여 논란'],
            ['title'=>'{stocks.name}사 총수 탑신병에 걸려 응급실행'],
            ['title'=>'{stocks.name}사 직원 A씨와 {users.nick_name} 주식 마포대교에서 팬티바람으로 티배깅댄스 추다 현장검거'],
            ['title'=>'{stocks.name}사 총수, 탕비실 커피믹스횡령 논란..'],
            ['title'=>'{stocks.name}사 총수,겨울배가 맛있다고 해 논란..'],
            ['title'=>'{users.nick_name}, 왜 나에대한  기준이 엄격하냐고 소리질러 논란'],
            ['title'=>'{stocks.name} 임직원, 탕수육 부먹논란 점화되어 대국민사과'],
            ['title'=>'{stocks.name} 임직원, 민트초코에 대한 트윗을 남겨 논란 재점화'],
            ['title'=>'{users.nick_name}, {stocks.name}사 직원들과 커플룩으로 출근 중..'],
            ['title'=>'{stocks.name}사 직원, 회사에서 코인 채굴 중 적발돼..'],
            ['title'=>'{users.nick_name}이 {stocks.name}사 주식으로 벌어들인 금액, 1억원 넘어서 논란..'],
            ['title'=>'{stocks.name}사 CEO, AI 로봇과의 결혼 발표..'],
            ['title'=>'{users.nick_name}이 {stocks.name}사 주식 투자 실패로 자택에서 포켓몬 잡는 중..'],
            ['title'=>'{stocks.name}사 직원, 배달의 민족에서 치킨 주문하다 적발..'],
            ['title'=>'{stocks.name}사 주식, 미친듯이 오르면서 펭귄의 춤을 추는 영상 공개..'],
            ['title'=>'{users.nick_name}, {stocks.name}사 직원과 코카콜라 전쟁 벌여..'],
            ['title'=>'{stocks.name}사, 버블티 맛에 취해 주식 대량 매수..'],
            ['title'=>'{users.nick_name}, 주식 투자하다 곰돌이 푸로 변신..'],
            ['title'=>'{stocks.name}사 직원, 아침에 커피 대신 과자 먹고 일어난 사연 공개..'],
            ['title'=>'{users.nick_name}, 주식으로 자산을 100배 불리겠다고 외쳐..'],
            ['title'=>'{stocks.name}사 CEO, 마리오 카트에서 직원들과 경쟁 중..'],
            ['title'=>'{stocks.name}사 직원, 투자 성공으로 대통령이라 불리며 인기..'],
            ['title'=>'{users.nick_name}, {stocks.name}사와 함께 행복한 하루 보내며 주식 거래..'],
            ['title'=>'{stocks.name}사 주식, 사랑의 불시착 캐릭터들로 홍보..'],
            ['title'=>'{users.nick_name}, {stocks.name}사와 함께 오징어 게임 재연..'],
            ['title'=>'{stocks.name}사 직원, 고기 사먹는 영상 공개 후 주식 상승..'],
            ['title'=>'{users.nick_name}, {stocks.name}사 주식으로 배민에서 배달 주문..'],
            ['title'=>'{stocks.name}사 직원, 리그 오브 레전드 대회 개최..'],
            ['title'=>'{users.nick_name}, {stocks.name}사 주식 투자 후 비타민D 먹으며 건강 관리..'],
            ['title'=>'{stocks.name}사, 할로윈 행사로 직원들 유니폼으로 변신..'],
            ['title'=>'{users.nick_name}, {stocks.name}사 주식으로 국내여행 다녀옴..'],
            ['title'=>'{stocks.name}사, 여름 맞이 수박 제공 후 매출 상승..'],
            ['title'=>'{users.nick_name}, {stocks.name}사 직원들과 자전거 타고 이동..'],
            ['title'=>'{stocks.name}사, 직원 생일에 케이크 제공..'],
            ['title'=>'{users.nick_name}, {stocks.name}사 직원들과 스카이 다이빙 시도..'],
            ['title'=>'{stocks.name}사, 겨울왕국 배경으로 직원 파티 개최..'],
            ['title'=>'{users.nick_name}, {stocks.name}사 주식으로 치킨 배달 중..'],
            ['title'=>'{stocks.name}사, 사랑의 불시착 이벤트로 직원들 보상..'],
            ['title'=>'{users.nick_name}, {stocks.name}사 직원들과 운동회 열어 대결 중..'],
            ['title'=>'{stocks.name}사, 봄맞이 벚꽃 구경으로 직원들 즐거움 만끽..'],
            ['title'=>'{users.nick_name}, {stocks.name}사와 포켓몬 게임 대결 중..'],
            ['title'=>'{stocks.name}사, 다이어트 프로그램으로 직원들 인기도 상승..'],
            ['title'=>'{users.nick_name}, {stocks.name}사 직원들과 커플룩으로 출근 중..'],
            ['title'=>'{stocks.name}사, 여름휴가로 직원들 인기 상승..'],
            ['title'=>'{users.nick_name}, {stocks.name}사 주식으로 영화관 관람 후 리포트 공개..'],
            ['title'=>'{stocks.name}사, 겨울왕국 배경으로 직원 파티 개최..'],
            ['title'=>'{users.nick_name}, {stocks.name}사와 함께 K-POP 댄스 영상 공개..'],
            ['title'=>'{stocks.name}사, 직원들 간의 단체 운동회 개최..'],
            ['title'=>'{users.nick_name}, {stocks.name}사 주식으로 국내여행 다녀옴..'],
            ['title'=>'{stocks.name}사, 직원들 간의 단체 운동회 개최..'],
            ['title'=>'{users.nick_name}, {stocks.name}사와 포켓몬 게임 대결 중..'],
            ['title'=>'{stocks.name}사, 다이어트 프로그램으로 직원들 인기도 상승..'],
            ['title'=>'{users.nick_name}, {stocks.name}사 직원들과 커플룩으로 출근 중..'],
            ['title'=>'{stocks.name}사, 직원들 간의 회식에 해산물 제공..'],
            ['title'=>'{users.nick_name}, {stocks.name}사 직원들과 주식 세미나 참석..'],
            ['title'=>'{stocks.name}사, 직원 건강 검진 실시 후 기념품 지급..'],
            ['title'=>'{users.nick_name}, {stocks.name}사 주식 투자로 가상화폐 거래 시작..'],
            ['title'=>'{stocks.name}사 직원, 자선 행사로 기부금 전달..'],
            ['title'=>'{users.nick_name}, {stocks.name}사 직원들과 요리 대회 개최..'],
            ['title'=>'{stocks.name}사, 신규 직원 환영회에서 다양한 간식 제공..'],
            ['title'=>'{users.nick_name}, {stocks.name}사 직원들과 클럽 활동 진행 중..'],
            ['title'=>'{stocks.name}사, 환경 보호 캠페인 참여..'],
            ['title'=>'{users.nick_name}, {stocks.name}사 직원들과 캠핑 여행 계획 중..'],
            ['title'=>'{stocks.name}사, 직원들 간의 온라인 게임 대회 개최..'],
            ['title'=>'{users.nick_name}, {stocks.name}사 주식으로 아트 전시회 관람..'],
            ['title'=>'{stocks.name}사, 직원들과 함께하는 봉사 활동 진행 중..'],
            ['title'=>'{users.nick_name}, {stocks.name}사 직원들과 바다 여행 다녀옴..'],
            ['title'=>'{stocks.name}사, 직원 복지 향상 프로그램 발표..'],
            ['title'=>'{users.nick_name}, {stocks.name}사 직원들과 미니 골프 대회 개최..'],
            ['title'=>'{stocks.name}사, 임직원 건강증진을 위한 체육대회 개최..'],
            ['title'=>'{users.nick_name}, {stocks.name}사 주식으로 애완동물 기부..'],
            ['title'=>'{stocks.name}사 직원, 사내 문화 체험 행사 참석..'],
            ['title'=>'{users.nick_name}, {stocks.name}사 직원들과 함께하는 사진 촬영..'],
            ['title'=>'{stocks.name}사, 재능 기부로 지역 사회에 도움..'],
            ['title'=>'{users.nick_name}, {stocks.name}사 직원들과 공동 저축 행사 참여..'],
            ['title'=>'{stocks.name}사, 인기 드라마에 협찬하여 주식 상승..'],
            ['title'=>'{users.nick_name}, {stocks.name}사 직원들과 함께하는 문화탐방..'],
            ['title'=>'{stocks.name}사, 지역 아동센터와 협력하여 문화행사 개최..'],
            ['title'=>'{users.nick_name}, {stocks.name}사와 함께하는 이색 마라톤 대회 참여..'],
            ['title'=>'{stocks.name}사, 스마트 오피스 도입으로 업무 환경 개선..'],
            ['title'=>'{users.nick_name}, {stocks.name}사 직원들과 함께하는 라이브 공연 관람..'],
            ['title'=>'{stocks.name}사, AI 기반 챗봇으로 주식 상담 중..'],
            ['title'=>'{users.nick_name}, {stocks.name}사 직원들과 VR 게임으로 스트레스 해소..'],
            ['title'=>'{stocks.name}사, 연말 파티에서 우주복 입고 등장..'],
            ['title'=>'{users.nick_name}, {stocks.name}사와 함께 버거 먹방 방송 중..'],
            ['title'=>'{stocks.name}사 직원, 회사에서 마술 쇼로 인기를 끌다..'],
            ['title'=>'{users.nick_name}, {stocks.name}사 직원들과 유튜브 챌린지 촬영..'],
            ['title'=>'{stocks.name}사, 직원들로 구성된 록 밴드 결성..'],
            ['title'=>'{users.nick_name}, {stocks.name}사 직원들과 함께 핑퐁 대회 개최..'],
            ['title'=>'{stocks.name}사 직원, 게임 중 독특한 캐릭터로 변신..'],
            ['title'=>'{users.nick_name}, {stocks.name}사 주식으로 모험 여행 떠나다..'],
            ['title'=>'{stocks.name}사, 직원들이 진행하는 토크쇼 시작..'],
            ['title'=>'{users.nick_name}, {stocks.name}사 주식 투자로 초능력 생김..'],
            ['title'=>'{stocks.name}사 직원, 트위치에서 게임 방송 중..'],
            ['title'=>'{users.nick_name}, {stocks.name}사와 함께 요가 클래스 진행 중..'],
            ['title'=>'{stocks.name}사, 직원 복지로 애완동물 데려오는 날 운영..'],
            ['title'=>'{users.nick_name}, {stocks.name}사와 함께 공원에서 피크닉 중..'],
            ['title'=>'{stocks.name}사, 독서 클럽 운영으로 직원들 간의 친목 도모..'],
            ['title'=>'{users.nick_name}, {stocks.name}사 직원들과 바베큐 파티 진행 중..'],
            ['title'=>'{stocks.name}사, 직원들 간의 스토리텔링 대회 개최..'],
            ['title'=>'{users.nick_name}, {stocks.name}사 직원들과 매직쇼 관람..'],
            ['title'=>'{stocks.name}사, 직원들이 만든 앱 출시..'],
            ['title'=>'{users.nick_name}, {stocks.name}사와 함께하는 패션쇼 참여..'],
            ['title'=>'{stocks.name}사, 직원들 간의 재능 경연 대회 개최..'],
            ['title'=>'{users.nick_name}, {stocks.name}사 주식으로 여행 블로그 운영 중..'],
            ['title'=>'{stocks.name}사, 자율주행차 테스트 중..'],
            ['title'=>'{users.nick_name}, {stocks.name}사와 함께 해양 쓰레기 정화 활동 중..'],
            ['title'=>'{stocks.name}사, 아트 페스티벌 참여로 화제..'],
            ['title'=>'{users.nick_name}, {stocks.name}사 직원들과 함께하는 펜션 여행..'],
            ['title'=>'{stocks.name}사, 직원들이 디자인한 마스코트 공개..'],
            ['title'=>'{users.nick_name}, {stocks.name}사 직원들과 전통놀이 대회 개최..'],
            ['title'=>'{stocks.name}사, 직원 건강 관리 앱 출시..'],
            ['title'=>'{users.nick_name}, {stocks.name}사와 함께 레트로 게임 마라톤..'],
            ['title'=>'{stocks.name}사, 직원들이 주최하는 영화 상영회 개최..'],
            ['title'=>'{users.nick_name}, {stocks.name}사 직원들과 함께 하는 낚시 여행..'],
            ['title'=>'{stocks.name}사, 직원들의 창의력 발휘하는 프로젝트 대회 진행..'],
            ['title'=>'{users.nick_name}, {stocks.name}사와 함께하는 명상 세션 진행..'],
            ['title'=>'{stocks.name}사, 직원들과 피트니스 챌린지 개최..'],
            ['title'=>'{users.nick_name}, {stocks.name}사와 함께 요리 대회 진행 중..'],
            ['title'=>'{stocks.name}사, 직원 복지로 연말 선물 지급..'],
            ['title'=>'{users.nick_name}, {stocks.name}사 직원들과 스케이트장 방문..'],
            ['title'=>'{stocks.name}사, 자연 보호 활동으로 인기..'],
            ['title'=>'{users.nick_name}, {stocks.name}사와 함께하는 드론 촬영 대회..'],
            ['title'=>'{stocks.name}사, 직원들이 만든 동영상 공모전 개최..'],
            ['title'=>'{users.nick_name}, {stocks.name}사와 함께하는 게임 나이트 진행 중..'],
            ['title'=>'{stocks.name}사, 주말 워크샵으로 팀 빌딩 실시..'],
        ];
        DB::table("news_words")->insert($wordAr);

        $stockAr=[
            ['name'=>'삼만전자','content'=>'삼만원이 돈이냐','stock_count'=>1000],
            ['name'=>'JOOGLE','content'=>'구글아님 죽을임','stock_count'=>1000],
            ['name'=>'스택 오빠플로우','content'=>'오빠 순서도 좀 그려줭','stock_count'=>1000],
            ['name'=>'공장초기화','content'=>'세상을 공장초기화한다!','stock_count'=>1000],
            ['name'=>'넹이뻐','content'=>'실은 뻥이요를 더 좋아합니다.','stock_count'=>1000],
            ['name'=>'즐택스','content'=>'즐!이나 먹으라지!','stock_count'=>1000],
        ];
        foreach($stockAr as $v){
            $stock_id=DB::table("stocks")->insertGetId($v);
            $price=rand(120,400)*100;
            DB::table("stock_historys")->insertGetId([
                'stock_id'=>$stock_id,
                'before_amount'=>$price,
                'now_amount'=>$price,
                'type'=>"START",
                'limit_percent'=>0,
            ]);
        }


        //DB::table("stock_historys")->insert($stockAr);
    }
}
